FROM ubuntu:rolling


COPY . /app

ADD https://ultralytics.com/assets/Arial.ttf https://ultralytics.com/assets/Arial.Unicode.ttf /root/.config/Ultralytics/

ENV DEBIAN_FRONTEND noninteractive
RUN apt update
RUN TZ=Etc/UTC apt install -y tzdata
RUN apt install --no-install-recommends -y python3-pip git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg g++
# RUN alias python=python3

RUN python3 --version

# Create working directory
RUN mkdir -p /usr/src/ultralytics
WORKDIR /usr/src/ultralytics

# Copy contents
# COPY . /usr/src/app  (issues as not a .git directory)
RUN git clone https://github.com/derronqi/yolov8-face.git /usr/src/ultralytics
ADD https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt /usr/src/ultralytics/

RUN mv /usr/src/ultralytics/ultralytics /app/ultralytics



# Install pip packages
RUN python -m pip install --upgrade pip wheel
RUN pip install --no-cache '.[export]' albumentations gsutil notebook \
        --extra-index-url https://download.pytorch.org/whl/cpu

# Cleanup
ENV DEBIAN_FRONTEND teletype



WORKDIR /app

#RUN pip install -r requirements

ENTRYPOINT [ "python" ]

CMD ["app.py" ]